FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80

# Install tools and their dependencies
RUN apt-get update && \
    apt-get install -y ffmpeg aria2 python3 python3-pip && \
    pip3 install yt-dlp

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["OhDl_server.csproj", "./"]
RUN dotnet restore "./OhDl_server.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "OhDl_server.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "OhDl_server.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "OhDl_server.dll"]
